from typing import Dict, Any, Optional
from app.security.audit import audit_logger
from app.tools.patient_records import get_patient_record

class MedGuardAgent:
    def __init__(self, agent_id: str = "agent-007", role: str = "clinical_assistant"):
        self.agent_id = agent_id
        self.role = role

    def execute_plan(
        self,
        session_id: str,
        user_id: str,
        user_role: str,
        patient_id: str,
        assigned_doctor_id: str,
        tool_name: str,
        user_prompt: str,
        capability_token: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Orchestrates tool execution by using verified capability tokens generated by the Gateway.
        """
        audit_logger.log_event(
            event_type="AGENT_TOOL_INVOCATION",
            session_id=session_id,
            user_id=user_id,
            agent_id=self.agent_id,
            tool_name=tool_name,
            status="EXECUTING",
            details={"patient_id": patient_id}
        )

        if not capability_token:
            return {
                "error": "Execution Blocked: Missing mandatory capability token.",
                "status": "DENIED"
            }

        if tool_name == "get_patient_record":
            try:
                result = get_patient_record(
                    capability_token=capability_token,
                    patient_id=patient_id
                )
                return {"status": "SUCCESS", "data": result}
            except PermissionError as e:
                audit_logger.log_event(
                    event_type="CAPABILITY_TOKEN_VERIFICATION_FAILED",
                    session_id=session_id,
                    user_id=user_id,
                    agent_id=self.agent_id,
                    tool_name=tool_name,
                    status="FAILED",
                    details={"error": str(e)}
                )
                return {"status": "FAILED", "error": str(e)}

        return {"status": "FAILED", "error": f"Unknown tool '{tool_name}'"}